[book]
authors = ["Enno Boland"]
language = "en"
src = "src"
title = "Rustcloak Operator"

[output.html]
git-repository-url = "https://github.com/DenktMit-eG/rustcloak-operator/"
edit-url-template = "https://github.com/DenktMit-eG/rustcloak-operator/edit/main/docs/{path}"
